pull_request_rules:
  - name: approve dependabot pull requests with build workflow
    conditions:
      - author~=dependabot\[bot\]
      - files~=^(Dockerfile.*|\.github/workflows/build\.yml|package-templates/)
      - check-success=build-repo-el7
      - check-success=build-repo-el8
    actions:
      review:
        type: APPROVE

  - name: approve dependabot pull requests without build workflow
    conditions:
      - author~=dependabot\[bot\]
      - -files~=^(Dockerfile.*|\.github/workflows/build\.yml|package-templates/)
    actions:
      review:
        type: APPROVE

  - name: merge dependabot pull requests
    conditions:
      - author~=dependabot\[bot\]
      - "#approved-reviews-by>=1"
    actions:
      merge:
        method: merge
